version: "3"

services:
  test:
    image: golang:1.10
    volumes:
      - .:/go/src/github.com/Applifier/go-bloomd
      - socketvolume:/tmp
    working_dir: /go/src/github.com/Applifier/go-bloomd
    command: go test -v -bench=. -coverprofile=coverage.out ./...
    links:
      - bloomd
    environment:
      BLOOMD_TCP: tcp://bloomd:8673
      BLOOMD_UNIX: unix:///tmp/bloomd.sock
      BLOOMD_SCHEMAS: TCP,UNIX

  bloomd:
    expose:
      - "8673"
    ports:
      - "8673:8673"
    build:
      dockerfile: ./scripts/Dockerfile_bloomd
      context: .
    volumes:
      - socketvolume:/tmp

volumes:
  socketvolume: {}